-- -------- < aula1exer2Evolucao4_Oracle > --------
--
--                    SCRIPT DE CRIACAO (DDL)
--
-- Data Criacao ...........: 20/10/2024
-- Autor(es) ..............: Lucas Lopes Frazão, Danilo César Tertuliano Melo, Larissa de Jesus Vieira, Carlos Eduardo Rodrigues
-- Banco de Dados .........: Oracle APEX 24.1.5
-- Base de Dados (nome) ...: WKSP_VRVR
--
-- PROJETO => 01 Base de Dados
--         => 09 Tabelas
-- 		   => 05 Sequences
--        
-- Ultimas Alteracoes
--   22/10/2024 => Ajusta para melhor apresentacao do script;
--              => Retirada de instrucoes que NAO sao SQL no script
--                 que nao aceita outras instrucoes que nao sejam SQL;
--              => Correcao para nomenclatura das restricoes de integridade
--                 para o padrao exigido na disciplina;
--              => Definicao completa do comportamento das FKs no script 
--   28/10/2024 => Criação das tabelas Area Gerencia e constitui;
--              => Correção das restrições
-- 	 04/11/2024 => Alteração do nome da base de dados para aula1exer2evolucao3
-- 				=> Exclusão da tabela inserido
-- 				=> Criação das tabelas GERENTE e EMPREGADO
-- 				=> Alteração nos atributos das tabelas
-- 				=> Adição do auto_increment
--   16/11/2024 => Adição do comportamento das FKs
--   21/11/2024 => Realizadas as alterações para a implemente da solução no SGBD ORACLE (APEX), como a assinatura especifica do aluno e SEQUENCEs.
-- ---------------------------------------------------------


CREATE SEQUENCE "CER_SEQ_GERENTE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE "CER_SEQ_EMPREGADO" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE "CER_SEQ_AREA" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE "CER_SEQ_PRODUTO" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
CREATE SEQUENCE "CER_SEQ_VENDA" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;


CREATE TABLE "CER_PESSOA" (
    "CPF" VARCHAR2(11) NOT NULL ENABLE,
    "SENHA" VARCHAR2(8) NOT NULL ENABLE,
    "NOME" VARCHAR2(255) NOT NULL ENABLE,
    CONSTRAINT "CER_PESSOA_PK" PRIMARY KEY ("CPF") USING INDEX ENABLE
);

CREATE TABLE "CER_GERENTE" (
    "IDGERENTE" NUMBER(5,0) DEFAULT "WKSP_VRVR"."CER_SEQ_GERENTE".NEXTVAL NOT NULL ENABLE,
    "EMAIL" VARCHAR2(255) NOT NULL ENABLE,
    "FORMACAO" VARCHAR2(255) NOT NULL ENABLE,
    "CPF" VARCHAR2(11) NOT NULL ENABLE,
    CONSTRAINT "CER_GERENTE_PK" PRIMARY KEY ("IDGERENTE") USING INDEX ENABLE
);

  CREATE TABLE "CER_EMPREGADO" 
   (	"MATRICULA" NUMBER DEFAULT "WKSP_VRVR"."CER_SEQ_EMPREGADO".NEXTVAL NOT NULL ENABLE, 
	"CEP" NUMBER NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(50) NOT NULL ENABLE, 
	"CIDADE" VARCHAR2(50) NOT NULL ENABLE, 
	"BAIRRO" VARCHAR2(50) NOT NULL ENABLE, 
    "COMPLEMENTO" VARCHAR2(50) NOT NULL ENABLE, 
	"NUMERO" NUMBER NOT NULL ENABLE, 
	"CPF" VARCHAR2(11) NOT NULL ENABLE, 
	 CONSTRAINT "CER_EMPREGADO_PK" PRIMARY KEY ("MATRICULA")
  USING INDEX  ENABLE
   ) ;

CREATE TABLE "CER_AREA" (
    "IDAREA" NUMBER(3,0) DEFAULT "WKSP_VRVR"."CER_SEQ_AREA".NEXTVAL NOT NULL ENABLE,
    "NOME" VARCHAR2(255) NOT NULL ENABLE,
    CONSTRAINT "CER_AREA_PK" PRIMARY KEY ("IDAREA") USING INDEX ENABLE
);

CREATE TABLE "CER_PRODUTO" (
    "IDPRODUTO" NUMBER(6,0) DEFAULT "WKSP_VRVR"."CER_SEQ_PRODUTO".NEXTVAL NOT NULL ENABLE,
    "NOME" VARCHAR2(255) NOT NULL ENABLE,
    "VALORUNITARIO" NUMBER(10,2) NOT NULL ENABLE,
    "IDAREA" NUMBER(3,0) NOT NULL ENABLE,
    CONSTRAINT "CER_PRODUTO_PK" PRIMARY KEY ("IDPRODUTO") USING INDEX ENABLE
);

CREATE TABLE "CER_VENDA" (
    "IDVENDA" NUMBER(6,0) DEFAULT "WKSP_VRVR"."CER_SEQ_VENDA".NEXTVAL NOT NULL ENABLE,
    "DATAVENDA" DATE NOT NULL ENABLE,
    "MATRICULA" NUMBER(10,0) NOT NULL ENABLE,
    CONSTRAINT "CER_VENDA_PK" PRIMARY KEY ("IDVENDA") USING INDEX ENABLE
);

CREATE TABLE "CER_TELEFONE" (
    "TELEFONE" VARCHAR2(11) NOT NULL ENABLE,
    "MATRICULA" NUMBER(10,0) NOT NULL ENABLE,
    CONSTRAINT "CER_TELEFONE_UK" UNIQUE ("TELEFONE", "MATRICULA") ENABLE
);

CREATE TABLE "CER_GERENCIA" (
    "IDGERENTE" NUMBER(5,0) NOT NULL ENABLE,
    "IDAREA" NUMBER(3,0) NOT NULL ENABLE
);

CREATE TABLE "CER_CONSTITUI" (
    "IDPRODUTO" NUMBER(6,0) NOT NULL ENABLE,
    "IDVENDA" NUMBER(6,0) NOT NULL ENABLE,
    "QUANTIDADE" NUMBER(5,0) NOT NULL ENABLE,
    CONSTRAINT "CER_CONSTITUI_UK" UNIQUE ("IDPRODUTO", "IDVENDA") ENABLE
);

ALTER TABLE "CER_GERENTE"
    ADD CONSTRAINT "CER_GERENTE_PESSOA_FK" FOREIGN KEY ("CPF")
    REFERENCES "CER_PESSOA"("CPF") ENABLE;

ALTER TABLE "CER_EMPREGADO"
    ADD CONSTRAINT "CER_EMPREGADO_PESSOA_FK" FOREIGN KEY ("CPF")
    REFERENCES "CER_PESSOA"("CPF") ENABLE;

ALTER TABLE "CER_PRODUTO"
    ADD CONSTRAINT "CER_PRODUTO_AREA_FK" FOREIGN KEY ("IDAREA")
    REFERENCES "CER_AREA"("IDAREA") ENABLE;

ALTER TABLE "CER_VENDA"
    ADD CONSTRAINT "CER_VENDA_EMPREGADO_FK" FOREIGN KEY ("MATRICULA")
    REFERENCES "CER_EMPREGADO"("MATRICULA") ENABLE;

ALTER TABLE "CER_TELEFONE"
    ADD CONSTRAINT "CER_TELEFONE_EMPREGADO_FK" FOREIGN KEY ("MATRICULA")
    REFERENCES "CER_EMPREGADO"("MATRICULA") ENABLE;

ALTER TABLE "CER_GERENCIA"
    ADD CONSTRAINT "CER_GERENCIA_GERENTE_FK" FOREIGN KEY ("IDGERENTE")
    REFERENCES "CER_GERENTE"("IDGERENTE") ENABLE;

ALTER TABLE "CER_GERENCIA"
    ADD CONSTRAINT "CER_GERENCIA_AREA_FK" FOREIGN KEY ("IDAREA")
    REFERENCES "CER_AREA"("IDAREA") ENABLE;

ALTER TABLE "CER_CONSTITUI"
    ADD CONSTRAINT "CER_CONSTITUI_PRODUTO_FK" FOREIGN KEY ("IDPRODUTO")
    REFERENCES "CER_PRODUTO"("IDPRODUTO") ENABLE;

ALTER TABLE "CER_CONSTITUI"
    ADD CONSTRAINT "CER_CONSTITUI_VENDA_FK" FOREIGN KEY ("IDVENDA")
    REFERENCES "CER_VENDA"("IDVENDA") ENABLE;

